### ISSUE TITLE
Development Workflow

### ISSUE THREAD

**Issue by jboetticher** [gaishimo/eas-widget-example#3]
Not sure how best to reach out, but figured this was one of them. What is your suggested workflow for developing and testing these widgets?

**Comment by gaishimo** [comment]
@jboetticher Excuse me, when you say workflow, what exactly do you want to know?

I think the Widget itself would have to be developed in Swift UI and Kotlin, but it would be the same flow as normal app development.

**Comment by jboetticher** [comment]
I was more so looking for developer workflow. For example, when I open up the android folder within widget via Android Studio, it doesn't give me a complete project that compiles. For now, I have a copy of an Android project that has similar code that I copy and paste, but that's probably not the best workflow.

I imagine something similar will happen when I open up the widget in xCode for Swift development.

Is there a good developer environment that you've found when developing these widgets while in their respective folders?

**Comment by gaishimo** [comment]
It is better to develop after running `expo prebuild`. After prebuild, ios and android folders will be created and can be opened in their complete state from Android Studio and XCode.

https://forums.expo.dev/t/ios-widget-extension-on-eas-build/63064/10?u=gaishimo-omoidasu
> Create a new app.
npx expo prebuild -p ios
Commit the “ios” directory to Git
Make your changes in Xcode
Run git diff to check what changes were made to the project files
Figure out how to make those same changes in a config plugin
